services:
  electron:
    build:
      context: ./app
      args:
        NODE_VERSION: ${NODE_VERSION}
    container_name: electron-app
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=${XAUTHORITY}
      - ELECTRON_DISABLE_SECURITY_WARNINGS=true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY}:${XAUTHORITY}
      - ./:/app
    devices:
      - /dev/dri:/dev/dri
    network_mode: "host"
    privileged: true
    tty: true

  web:
    build:
      context: ./web
      args:
        PHP_VERSION: ${PHP_VERSION}
    container_name: ${PROJECT_NAME}_apache
    restart: unless-stopped
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./web:/var/www/html 
    depends_on:
      - db

  db:
    build:
      context: ./mysql
    container_name: ${PROJECT_NAME}_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./mysql/dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: ${PROJECT_NAME}_pma
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db 
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db